## catalog of libraries and plugins used to build the jolt-jni-docs project

[versions]

checkstyle = "12.1.1"
joltjni = "3.5.0"
luajava = "4.0.2"
lwjgl = "3.3.6"

[libraries]

groovy-all = "org.apache.groovy:groovy-jsr223:5.0.2"

jolt-jni-linux64 = { module = "com.github.stephengold:jolt-jni-Linux64", version.ref = "joltjni" }
jolt-jni-linux64fma = { module = "com.github.stephengold:jolt-jni-Linux64_fma", version.ref = "joltjni" }
jolt-jni-linuxarm32hf = { module = "com.github.stephengold:jolt-jni-Linux_ARM32hf", version.ref = "joltjni" }
jolt-jni-linuxarm64 = { module = "com.github.stephengold:jolt-jni-Linux_ARM64", version.ref = "joltjni" }
jolt-jni-macosx64 = { module = "com.github.stephengold:jolt-jni-MacOSX64", version.ref = "joltjni" }
jolt-jni-macosxarm64 = { module = "com.github.stephengold:jolt-jni-MacOSX_ARM64", version.ref = "joltjni" }
jolt-jni-windows64 = { module = "com.github.stephengold:jolt-jni-Windows64", version.ref = "joltjni" }
jolt-jni-windows64avx2 = { module = "com.github.stephengold:jolt-jni-Windows64_avx2", version.ref = "joltjni" }

jruby = "org.jruby:jruby-complete:9.4.14.0"
jsnaploader = "io.github.electrostat-lab:snaploader:1.1.1-stable"
jython = "org.python:jython-slim:2.7.4"
luaj-jse = "org.luaj:luaj-jse:3.0.1"

luajava-base = { module = "party.iroiro.luajava:luajava", version.ref = "luajava" }
luajava-jsr223 = { module = "party.iroiro.luajava:jsr223", version.ref = "luajava" }
luajava-lua54 = { module = "party.iroiro.luajava:lua54", version.ref = "luajava" }
luajava-lua54-platform = { module = "party.iroiro.luajava:lua54-platform", version.ref = "luajava" }

lwjgl = { module = "org.lwjgl:lwjgl", version.ref = "lwjgl" }
lwjgl-assimp = { module = "org.lwjgl:lwjgl-assimp", version.ref = "lwjgl" }
lwjgl-glfw = { module = "org.lwjgl:lwjgl-glfw", version.ref = "lwjgl" }
lwjgl-opengl = { module = "org.lwjgl:lwjgl-opengl", version.ref = "lwjgl" }

nashorn-core = "org.openjdk.nashorn:nashorn-core:15.7"
scala-library = "org.scala-lang:scala3-library_3:3.7.4"
sport-jolt = "com.github.stephengold:sport-jolt:0.9.13"

[bundles]

[plugins]

diktat = { id = "com.saveourtool.diktat", version = "2.0.0" }
download = { id = "de.undercouch.download", version = "5.6.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.2.21" }
