---
# GitHub Actions workflow for commits pushed to the jolt-jni-docs repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java17-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: actions/checkout@v6
      - uses: gradle/actions/wrapper-validation@v5
      - run: ./gradlew build javadoc HelloJoltJni -x :java-apps:checkstyleMain --console=plain --stacktrace
      - uses: DeLaGuardo/setup-clojure@13.5.2
        with:
          lein: 2.12.0
      - run: lein run

  Java17-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-15-intel
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: actions/checkout@v6
      - run: ./gradlew build javadoc HelloJoltJni -x :java-apps:checkstyleMain --console=plain --stacktrace
      - uses: DeLaGuardo/setup-clojure@13.5.2
        with:
          lein: 2.12.0
      - run: lein run

  Java21-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-15
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: actions/checkout@v6
      - run: ./gradlew build javadoc HelloJoltJni --console=plain --stacktrace
      - uses: DeLaGuardo/setup-clojure@13.5.2
        with:
          lein: 2.12.0
      - run: lein run

  Java25-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2025
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 25
      - uses: actions/checkout@v6
      - run: ./gradlew build javadoc HelloJoltJni --console=plain --stacktrace
        shell: bash
      - uses: DeLaGuardo/setup-clojure@13.5.2
        with:
          lein: 2.12.0
      - run: lein run
        shell: bash
